### ISSUE TITLE
정산방(Space) 공유+참가하기 Flow

### ISSUE THREAD

**Issue by chaneeii** [Team-Trit/donworry-ios#167]
정산방 공유하기 로직 정리해둘게요!

<img width="1368" alt="스크린샷 2022-09-13 오후 11 51 56" src="https://user-images.githubusercontent.com/63157395/189934061-7e6df0a3-20ad-47d6-9ed6-15ecf4d52d3c.png">

1. 링크공유를 누르면
2.  액티비티 시트가 뜬다
3. 공유를 하게 되면 사용자가 링크를 받게됨
    1. 안깔렸다면 앱스토어
    2. 깔렸다면 방으로 직접초대
        1. 회원가입이 되어있다면 → 홈 뜨고 방으로 push
        2. 회원가입 로그인 안되어있다면 앱만 실행됨

### TODO
@chaneeii 
- [x] #174
  - [x] 파이어베이스 프로젝트 설정하기 ( 파베 플젝 콘솔추가 / Package 설치)
  - [x] 파이어베이스 다이나믹링크 작업 (app id 및 team id 필요)
  - [x] App link 생성 및 디펜던시 추가
  - [x] App Custom Scheme 추가 
  - [x] 딥링크연결 및 url 처리 
  - [x] 공유하기

@wody-d 
- [x] #175
