### ISSUE TITLE
정산항목 카드 꾸미기

### ISSUE THREAD

**Issue by chaneeii** [Team-Trit/donworry-ios#17]
<img width="992" alt="스크린샷 2022-08-07 오후 4 27 04" src="https://user-images.githubusercontent.com/63157395/183280119-1c03dce5-2fdd-493f-aae5-8e2fcb7b59dd.png">

## Story 
> 사용자는 정산 상세내역으로 정산카드를 꾸미고 실시간으로 카드가 꾸며지는 것을 볼 수 있다.

- UITableView로 테이블 뷰를 짠다.
- 헤더에 카드를 넣는다.
- 정산카드 꾸미기 컨텐츠 넣기
  - 배경선택 : 컬러피커 구현
  - 날짜선택 : 달력 넣기
  - 계좌번호입력 : 은행선택모달 및 텍스트 필드 입력 가능하게 (@LentoAssai 의 은행선택모달 훔쳐쓰기)
  - 파일추가 : 이미지 피커 넣기 
- 정산카드 꾸미기 내용이랑 카드랑 연동되서 변경하게 만들기

## Tasks
- [x] CardDeco 화면 레이아웃 구현 
- [x] CardDeco 테이블UI 및 카드 꾸미기 기능
- [x] 계좌관련 Modal 및 데이터 연동 작업
- [x] #87

## ref

- 컬러피커 
  - https://iosexample.com/a-customizable-color-picker-for-ios-in-swift/
