### ISSUE TITLE
UI 작업

### ISSUE THREAD

**Issue by LentoAssai** [Team-Trit/donworry-ios#22]
## 개요
회원가입 스토리의 UI를 구현합니다.

## Todo
- [x] 로그인 버튼 그림자 제거
- [x] 은행 선택 화면에서 스크롤 시 검색 창 고정 및 은행 섹션 조금 더 빨리 사라지게 수정
- [x] Navigation 및 Modal로 화면 연결
- [ ] 은행 선택 시 UserInfoView에 반영
- [x] 텍스트필드에 입력할 때 글자 수 제한
- [ ] 애플, 구글, 카카오 소셜 로그인 기능
- [ ] 이용 약관 내용 수정
- [x] 이용 약관 셀 클릭 수정
- [x] 이용 약관 확인 모달 추가
