### ISSUE TITLE
정산항목 이름설정 UI 구현

### ISSUE THREAD

**Issue by chaneeii** [Team-Trit/donworry-ios#62]
### TODO
- [x] UI 구현
- [x] 정산내역을 초기 추가하는 경우 / 수정하는 경우 분기 처리
- [x] 화면 영역 터치시 키보드 닫히도록 구현 
- [x] Icon Asset 추가
