### ISSUE TITLE
회원가입 

### ISSUE THREAD

**Issue by samsung-ga** [Team-Trit/donworry-ios#7]
<img width="872" alt="스크린샷 2022-08-04 오전 12 53 09" src="https://user-images.githubusercontent.com/56102421/182653356-0dc827d4-0f6a-4856-9f52-99a3f5a1c5c8.png">

## Task
- [x] #22
- [x] #54
- [x] #56
- [x] #58 (+ ConfirmTerm UI 작업)
- [x] 디자인 시스템 재사용 뷰 추가
- [ ] 소셜 로그인 기능 구현
- [x] #69

## Todo
- 은행 선택뷰를 추가해야합니다.
- 닉네임은 중복 체크가 필요합니다.
- 계좌번호가 유효한지 체크가 필요합니다.
