### ISSUE TITLE
정산방리스트 및 송금(입금)카드 확인하는 화면 작업 

### ISSUE THREAD

**Issue by samsung-ga** [Team-Trit/donworry-ios#8]
<img width="400" alt="스크린샷 2022-08-04 오전 12 56 47" src="https://user-images.githubusercontent.com/56102421/182654490-d0a96da8-84d6-413c-974a-de575cddb9db.png">

- 정산방이 있을 때와 없을 때의 구분 로직이 필요합니다.
- 카드는 2개 이상부터 원을 그리며 나옵니다. 

## Task

- [x] 정산방리스트 및 송금(입금)카드 확인하는 화면 UI 그리기 (엠티뷰 포함) 
- [x] 정산방리스트 및 송금(입금)카드 확인하는 화면 비즈니스 로직 구성하기
- [x] 정산방리스트 및 송금(입금)카드 확인하는 화면 서비스 구현
- [x] 정산방리스트 및 송금(입금)카드 확인하는 화면 서버 API 연결 및 서비스 개선
